// Generated from apps/table/src-tauri by tauri-specta. Do not edit;
// run `bun run schema` after changing the command surface.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Rank the compendium against `query` for a viewer of `viewer` tier who
	 *  reads the rules of `version` (one hit per thing; the version's own entry
	 *  when it has one, else another version's, which carries its version).
	 */
	search: (query: string, viewer: Visibility, limit: number | null, filters: Filter[] | null, version: string | null) => typedError<SearchResponse, CommandError>(__TAURI_INVOKE("search", { query, viewer, limit, filters, version })),
	/**
	 *  One entry as `viewer` may see it. With a `version`, the same thing in
	 *  that rule version when it exists there, else the entry asked for: a
	 *  page turns to the reader's version when they switch.
	 */
	getEntry: (id: EntryId, viewer: Visibility, version: string | null) => typedError<Entry, CommandError>(__TAURI_INVOKE("get_entry", { id, viewer, version })),
	/**  The manifests of every module in the compendium, for the credits view. */
	modules: () => typedError<Manifest[], CommandError>(__TAURI_INVOKE("modules")),
	/**
	 *  The system the compendium was seeded for: its categories, kinds,
	 *  facets and the tray's controls. `None` when the seeder was given none.
	 */
	system: () => typedError<{
	id: string,
	name: string,
	/**
	 *  The rule versions the system's content comes in, by id ("2014",
	 *  "2024"), in the order a switch shows them. Each person reads one
	 *  (design.md §3 "Two rule versions, one compendium").
	 */
	versions?: { [key in string]: VersionSpec },
	/**  Category id to label: the tabs of the box, in this order. */
	categories?: { [key in string]: string },
	/**  Entry kind to what it is called and where it is grouped. */
	kinds?: { [key in string]: KindSpec },
	/**  Per kind, facet name to how it is read from `data`. */
	facets?: { [key in string]: { [key in string]: FacetSpec } },
	/**  Per kind, the tray's controls in order. */
	controls?: { [key in string]: ControlSpec[] },
	/**  Per kind, the lists in `data` whose items are named parts. */
	parts?: { [key in string]: PartSpec[] },
} | null, CommandError>(__TAURI_INVOKE("system")),
	/**
	 *  The text values each facet holds across the compendium, for the tray's
	 *  chips: schools, creature types, categories.
	 */
	facetValues: () => typedError<{ [key in string]: string[] }, CommandError>(__TAURI_INVOKE("facet_values")),
	/**  The scene the board shows. */
	getScene: () => typedError<Scene, CommandError>(__TAURI_INVOKE("get_scene")),
	/**  Every scene in the library, by name. */
	listScenes: () => typedError<SceneSummary[], CommandError>(__TAURI_INVOKE("list_scenes")),
	/**  Switch the table to the scene `id`. */
	openScene: (id: string) => typedError<Scene, CommandError>(__TAURI_INVOKE("open_scene", { id })),
	/**
	 *  Create a scene with `strokes` drawn, and switch to it: blank, or a
	 *  reference drawing, or later an import.
	 */
	createScene: (name: string, strokes: Stroke[]) => typedError<Scene, CommandError>(__TAURI_INVOKE("create_scene", { name, strokes })),
	/**  Commit a token's move: the release of a drag, or a keyboard step. */
	moveToken: (id: string, col: number, row: number, facing: number) => typedError<Scene, CommandError>(__TAURI_INVOKE("move_token", { id, col, row, facing })),
	/**  Stand a compendium entry on a cell as a new token. */
	placeEntry: (id: EntryId, col: number, row: number) => typedError<Scene, CommandError>(__TAURI_INVOKE("place_entry", { id, col, row })),
	/**  Take a token off the board. */
	removeToken: (id: string) => typedError<Scene, CommandError>(__TAURI_INVOKE("remove_token", { id })),
	/**
	 *  Add a stroke to the end of the scene's record: the release of a Build
	 *  mode gesture.
	 */
	addStroke: (stroke: Stroke) => typedError<Scene, CommandError>(__TAURI_INVOKE("add_stroke", { stroke })),
	/**
	 *  Take one stroke out of the record by its position; the rest keep
	 *  their order.
	 */
	removeStroke: (index: number) => typedError<Scene, CommandError>(__TAURI_INVOKE("remove_stroke", { index })),
	/**
	 *  Take back the last stroke drawn. With nothing to take back the scene
	 *  comes back unchanged.
	 */
	undoStroke: () => typedError<Scene, CommandError>(__TAURI_INVOKE("undo_stroke")),
	/**  Choose how the scene shows height over its picture. */
	setDisplay: (display: HeightDisplay) => typedError<Scene, CommandError>(__TAURI_INVOKE("set_display", { display })),
};

/* Types */
/**
 *  One cell of a switch rail: the facet and value it stands for. A cell
 *  without a value stands for a yes.
 */
export type Cell = {
	facet: string,
	value?: FacetValue,
	label: string,
};

/**  A block of cells, both corners inclusive. */
export type CellRect = {
	col0: number,
	row0: number,
	col1: number,
	row1: number,
};

/**  Why a command could not answer. */
export type CommandError = 
/**  No compendium is installed; nothing to search. */
{ kind: "no-compendium" } | 
/**  No entry with that id, or none the viewer may see. */
{ kind: "not-found"; id: string } | 
/**  The store failed underneath. */
{ kind: "store"; message: string } | 
/**  The scene refused the change, or could not be saved. */
{ kind: "scene"; message: string };

/**  How a facet filter compares. */
export type Compare = "eq" | "lt" | "le" | "gt" | "ge";

/**
 *  The five controls of the tray. `Rail` paints spans over an ordered
 *  scale; `Switch` is the same strip with each cell its own switch.
 */
export type ControlKind = "rail" | "switch" | "slider" | "chips" | "select";

/**  One control of the tray. */
export type ControlSpec = {
	control: ControlKind,
	label: string,
	/**  The facet a rail, slider, chips or select edits. */
	facet?: string | null,
	/**
	 *  The ordered values of a rail, slider or select. Chips take theirs
	 *  from the data.
	 */
	stops?: Stop[],
	/**
	 *  The cells of a switch rail, as rows shown side by side. A manifest
	 *  may write one flat row.
	 */
	cells?: Cell[][],
	/**  A control shown beside this one (the switches beside a range slider). */
	beside?: ControlSpec | null,
};

/**  One edge of a cell, named by the cell and the side. */
export type Edge = {
	col: number,
	row: number,
	side: Side,
};

/**  One compendium entry: the system-agnostic envelope plus the system's data. */
export type Entry = {
	id: EntryId,
	/**  The entry's category within its system: `monster`, `spell`, `item`, and so on. */
	type: string,
	name: string,
	/**  Provenance: the book, module, or homebrew collection the entry came from. */
	source: string,
	/**
	 *  The rule version the entry belongs to, its module's: "2014", "2024".
	 *  An entry is a version of a thing, and `<kind>:<slug>` is the thing's
	 *  identity across versions (design.md §3 "Two rule versions"). Filled
	 *  from the module manifest when the module is read; empty means unversioned.
	 */
	version?: string,
	/**
	 *  Every rule version this thing exists in, its own among them, so a
	 *  page can offer the switch. Filled when one entry is read; never
	 *  stored, and a list carries none.
	 */
	versions?: string[],
	tags: string[],
	/**  Who may see the entry at all: its name, tags, and body. */
	visibility: Visibility,
	/**  Who may see `data`. A monster can be known by name while its statblock stays DM-only. */
	data_visibility: Visibility,
	/**  Prose body, markdown. */
	body: string,
	/**
	 *  The body as HTML, rendered by the core's one renderer as the entry
	 *  leaves the store (`render`). Empty on the way in and never stored:
	 *  the markdown is the record, the HTML is derived from it.
	 */
	html?: string,
	/**
	 *  The named parts of `data` as the page shows them, rendered as the
	 *  entry leaves the store from the lists the system manifest names.
	 *  Empty on the way in and never stored; empty whenever `data` is
	 *  hidden from the viewer, since they are read out of it.
	 */
	sections?: Section[],
	/**  The per-system structured blob; its schema belongs to the game system, not the envelope. */
	data: JsonValue,
	/**  Filterable facts read from `data` by the system manifest at seed time. */
	facets?: { [key in string]: FacetValue },
	/**
	 *  Named parts of `data` read by the system manifest at seed time, so
	 *  search can find an entry by a trait, an action, or a feature.
	 */
	parts?: Part[],
};

/**  Stable identifier of an entry; links never break because ids never change. */
export type EntryId = string;

/**  How one facet is read from an entry's `data`, and the words that name it. */
export type FacetSpec = {
	/**  Dotted path into `data`. */
	path: string,
	type: FacetType,
	/**  Words the parser accepts for the facet's name. */
	words?: string[],
	/**  Words that stand for one value of the facet (`cantrip` for level 0). */
	aliases?: { [key in string]: FacetValue },
	/**
	 *  Text facets only: the value is the first of these words found in the
	 *  text at `path`, so one string can feed several facets.
	 */
	pick?: string[],
	/**
	 *  Number facets only: words in another field that stand for a number
	 *  beyond any real one (a range of sight).
	 */
	sentinels?: Sentinels | null,
	/**  Display unit, never stored with the value. */
	unit?: string | null,
};

export type FacetType = "number" | "text" | "bool";

/**
 *  A facet: one filterable fact about an entry, read from its data by the
 *  system's manifest at seed time (`level`, `school`, `cr`, `ritual`), so
 *  search can answer `level<=3` without opening the data.
 */
export type FacetValue = number | null | string | boolean;

/**
 *  A filter: what an entry must satisfy to be listed at all. Values are
 *  normalised like everything else. A list of filters is a conjunction;
 *  `Any` and `Not` give it the rest of the shapes a phrase can take.
 */
export type Filter = { filter: "kind"; value: string } | { filter: "tag"; value: string } | { filter: "source"; value: string } | 
/**  A facet of the entry's data: `level<=3`, `school:evocation`. */
{ filter: "facet"; name: string; compare: Compare; value: string } | 
/**  At least one of these passes. */
{ filter: "any"; items: Filter[] } | 
/**  This one does not pass. */
{ filter: "not"; item: Filter };

/**  A square grid, in map pixels; hex grids arrive with hexpunk's lattice. */
export type Grid = {
	cell_size: number,
	origin_x: number,
	origin_y: number,
	cols: number,
	rows: number,
};

/**  What a cell of ground is for movement. */
export type GroundState = "ground" | 
/**  Double cost to cross. */
"difficult" | 
/**  Fliers only: the gap between islands, a floor a spell took. */
"air" | 
/**  Nobody: outside the scene. */
"void";

/**  How a scene shows height over its picture. */
export type HeightDisplay = {
	mode: HeightMode,
	/**  The overlay's opacity, 0 to 100. */
	strength: number,
};

/**
 *  The ways height can show: a soft shadow on the low side, a tint per
 *  band, a hairline with edge tags, or nothing but the numbers.
 */
export type HeightMode = "shaded" | "washed" | "marked" | "data";

/**  One row of a search result. */
export type Hit = {
	id: EntryId,
	type: string,
	name: string,
	source: string,
	/**
	 *  The rule version of the entry shown. One hit per thing: the viewer's
	 *  version when the thing exists in it, else another version standing
	 *  in, which the tile badges by comparing this with the viewer's.
	 */
	version: string,
	tags: string[],
	/**
	 *  The part the query found this entry by, when its best match was a
	 *  trait, an action or a feature rather than the entry itself.
	 */
	part: Part | null,
	/**
	 *  Rule 3 rungs less the rule 5 bonus; lower is better. Comparable only
	 *  within one result list.
	 */
	rank: number,
	/**  Rule 4 penalties; lower is better. */
	penalty: number,
};

/**
 *  The TypeScript shape of `serde_json::Value`, used only as a type witness
 *  through `#[specta(type = JsonValue)]`; the fields themselves stay
 *  `serde_json::Value`. The exporter refuses the 64-bit integers inside
 *  `serde_json::Number` because JavaScript would truncate them; JSON numbers
 *  are JavaScript numbers on that side whatever we say, so this names that
 *  truth once. JSON `null` needs no variant: specta renders an untagged enum
 *  with `null` in its union.
 */
export type JsonValue = boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

/**
 *  What a kind is called, where the box groups it, which words mean it,
 *  and what an entry of it may be seen by unless the entry says otherwise.
 */
export type KindSpec = {
	name: string,
	category: string,
	words?: string[],
	visibility?: Visibility | null,
	data_visibility?: Visibility | null,
};

/**  The manifest at a module's root, `module.json`. */
export type Manifest = {
	id: string,
	name: string,
	system: string,
	systemVersion: string,
	version: string,
	license: string,
	/**  The notice the licence requires; shown in the credits view. */
	attribution: string,
	/**  Free-form provenance: where the content was imported from. */
	upstream?: JsonValue | null,
};

/**  The map image under the grid. */
export type MapImage = {
	url: string,
	width: number,
	height: number,
};

/**
 *  The note beside a part's name: a label and a path to what follows it,
 *  which may cross a list with `*` and reads every match: "Level" over
 *  `gained_at.*.level` gives "Level 4, 8, 12, 16".
 */
export type NoteSpec = {
	path: string,
	label: string,
};

/**
 *  A window's size: a large one is forcible in play, dived through open or
 *  smashed shut; a small one is sight only.
 */
export type OpeningSize = "small" | "large";

/**
 *  A named part of an entry's data: a creature's trait or action, a
 *  class's feature. The manifest names the lists that carry them, the
 *  seeder stores their names, and search matches them as a field, so
 *  "pack tactics" finds its bearers and the tile can say which part hit.
 */
export type Part = {
	/**  What kind of part, as the system calls it: "Trait", "Action". */
	label: string,
	name: string,
};

/**
 *  A list inside `data` whose items carry a name and a text: `traits`,
 *  `actions`, a class's `features`. Each item is a searchable part and a
 *  section of the page.
 */
export type PartSpec = {
	/**  Dotted path to the list. */
	path: string,
	/**  The heading the parts sit under: "Traits", "Actions", "Features". */
	label: string,
	/**  The item field holding the name. */
	key?: string,
	/**  The item field holding the text, markdown. */
	text?: string,
	/**
	 *  Fields an item must match to belong, when given: a creature's one
	 *  `actions` list holds its legendary actions too, told apart by
	 *  `action_type`, so one list can feed several headings.
	 */
	when?: { [key in string]: string },
	/**
	 *  Dotted path to a number the items are sorted by, when given: a
	 *  class feature by the level it is gained at. Items without one keep
	 *  their order, after the rest.
	 */
	order?: string | null,
	/**  A word to show beside each part's name, read from the item. */
	note?: NoteSpec | null,
};

/**
 *  A point in cell units from the grid's origin: (1.5, 2.5) is the centre
 *  of column 1, row 2.
 */
export type Point = {
	x: number | null,
	y: number | null,
};

/**  A scene as the board shows it. */
export type Scene = {
	id: string,
	name: string,
	grid: Grid,
	map: MapImage | null,
	tokens: Token[],
	/**
	 *  What the DM drew over the picture, in the order drawn. This is the
	 *  record; the board derives the ground, the edges and the field from
	 *  it.
	 */
	strokes: Stroke[],
	/**  How this scene shows height over its picture. */
	display: HeightDisplay,
	/**  Counter behind the ids this scene mints for new tokens. */
	next_token: number,
};

/**  A scene as the list shows it. */
export type SceneSummary = {
	id: string,
	name: string,
};

/**  A ranked search result with the time the core spent on it. */
export type SearchResponse = {
	hits: Hit[],
	/**  Time spent in the core, in microseconds. */
	elapsed_us: number,
	/**  How many entries the catalogue held when it answered. */
	catalogue_size: number,
	/**
	 *  What the parser made of the typed text: the stretches that became
	 *  filters, and those set aside as meaning nothing here.
	 */
	understood: Understood[],
};

/**
 *  A named part of an entry as the page shows it: one trait, action or
 *  feature out of `data`, its text rendered. Read out by the system manifest
 *  as the entry leaves the store; never stored.
 */
export type Section = {
	/**  The heading the section sits under: "Traits", "Actions", "Features". */
	label: string,
	name: string,
	/**
	 *  A word beside the name, when the manifest asks for one: the level a
	 *  class feature is gained at. Empty otherwise.
	 */
	note: string,
	/**  The section's text as HTML, from the core's one renderer. */
	html: string,
};

/**  Words at `path` that stand for a number. */
export type Sentinels = {
	path: string,
	values: { [key in string]: number | null },
};

/**
 *  An area drawn in cells: a block of cells, a free shape traced as a
 *  polygon, or a brush's dabs.
 */
export type Shape = { kind: "rect"; rect: CellRect } | 
/**  The polygon through these corners, in order. */
{ kind: "free"; points: Point[] } | 
/**  A disc of `radius` cells around each dab. */
{ kind: "brush"; points: Point[]; radius: number | null };

/**
 *  The two sides that name every edge once: a cell's east edge is its
 *  neighbour's west, its south edge the one below's north.
 */
export type Side = "east" | "south";

/**
 *  One value on a rail, slider or select, with the label it shows when
 *  the value itself will not do.
 */
export type Stop = {
	value: FacetValue,
	label?: string | null,
};

/**  One addition to the map: an ink, its shape, and who may see it. */
export type Stroke = 
/**  What can be stood on, and by whom. */
{ ink: "ground"; shape: Shape; state: GroundState; visibility: Visibility } | 
/**  An opening in a cell edge: a door, an arch, a window. */
{ ink: "threshold"; edge: Edge; kind: ThresholdKind; state: ThresholdState; size: OpeningSize; visibility: Visibility } | 
/**  Solid edges. Nothing derives walls; the DM draws every one. */
{ ink: "wall"; shape: WallShape; visibility: Visibility } | 
/**
 *  An amount written into the elevation field, in the system's
 *  distance unit.
 */
{ ink: "height"; shape: Shape; value: number; visibility: Visibility } | 
/**
 *  Where a change of height is walked rather than climbed: stairs,
 *  ramps, ladders, lifts.
 */
{ ink: "level-change"; shape: Shape; visibility: Visibility } | 
/**  Ink with no rules meaning. */
{ ink: "free"; shape: Shape; visibility: Visibility };

/**  The system manifest. */
export type SystemManifest = {
	id: string,
	name: string,
	/**
	 *  The rule versions the system's content comes in, by id ("2014",
	 *  "2024"), in the order a switch shows them. Each person reads one
	 *  (design.md §3 "Two rule versions, one compendium").
	 */
	versions?: { [key in string]: VersionSpec },
	/**  Category id to label: the tabs of the box, in this order. */
	categories?: { [key in string]: string },
	/**  Entry kind to what it is called and where it is grouped. */
	kinds?: { [key in string]: KindSpec },
	/**  Per kind, facet name to how it is read from `data`. */
	facets?: { [key in string]: { [key in string]: FacetSpec } },
	/**  Per kind, the tray's controls in order. */
	controls?: { [key in string]: ControlSpec[] },
	/**  Per kind, the lists in `data` whose items are named parts. */
	parts?: { [key in string]: PartSpec[] },
};

/**
 *  What kind of opening a threshold is. Windows pass sight whatever their
 *  state; a frosted one blurs it.
 */
export type ThresholdKind = "door" | "arch" | "window" | "frosted";

/**  A threshold's state. A secret one is the DM's alone until it is found. */
export type ThresholdState = "open" | "closed" | "locked" | "secret";

/**  Something standing on a cell. */
export type Token = {
	id: string,
	name: string,
	/**  The short mark drawn on the disc: initials, at most two letters. */
	label: string,
	col: number,
	row: number,
	/**  Degrees clockwise from north. */
	facing: number,
	/**  The compendium entry this token stands for, when it stands for one. */
	entry: EntryId | null,
	visibility: Visibility,
};

/**
 *  A stretch of the typed query the parser dealt with: the filter it
 *  became, or nothing when the stretch was set aside as meaning nothing
 *  here (a connective on its own, a word no entry has).
 */
export type Understood = {
	/**  Char offsets into the typed text. */
	start: number,
	end: number,
	filter: Filter | null,
	/**
	 *  The tray said otherwise about this facet, so the words were set
	 *  aside; they stay in the text, greyed.
	 */
	overruled?: boolean,
};

/**  One rule version of a system. */
export type VersionSpec = {
	name: string,
};

/**
 *  Who may see something. Ordered from most open to most restricted, so a
 *  viewer sees everything at or below their own tier.
 */
export type Visibility = 
/**  Anyone, including a player who has never met the thing. */
"world" | 
/**  The party: players at the table. */
"party" | 
/**  The DM only. */
"dm";

/**  A wall as drawn: along one run of edges, or the four sides of a rect. */
export type WallShape = { kind: "line"; edges: Edge[] } | { kind: "rect"; rect: CellRect };

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

