// Generated from apps/table/src-tauri by tauri-specta. Do not edit;
// run `bun run schema` after changing the command surface.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Rank the compendium against `query` for a viewer of `viewer` tier. */
	search: (query: string, viewer: Visibility, limit: number | null) => typedError<SearchResponse, CommandError>(__TAURI_INVOKE("search", { query, viewer, limit })),
	/**  One entry as `viewer` may see it. */
	getEntry: (id: EntryId, viewer: Visibility) => typedError<Entry, CommandError>(__TAURI_INVOKE("get_entry", { id, viewer })),
	/**  The manifests of every module in the compendium, for the credits view. */
	modules: () => typedError<Manifest[], CommandError>(__TAURI_INVOKE("modules")),
	/**  The scene the board shows. */
	getScene: () => typedError<Scene, CommandError>(__TAURI_INVOKE("get_scene")),
	/**  Commit a token's move: the release of a drag, or a keyboard step. */
	moveToken: (id: string, col: number, row: number, facing: number) => typedError<Scene, CommandError>(__TAURI_INVOKE("move_token", { id, col, row, facing })),
	/**  Stand a compendium entry on a cell as a new token. */
	placeEntry: (id: EntryId, col: number, row: number) => typedError<Scene, CommandError>(__TAURI_INVOKE("place_entry", { id, col, row })),
	/**  Take a token off the board. */
	removeToken: (id: string) => typedError<Scene, CommandError>(__TAURI_INVOKE("remove_token", { id })),
};

/* Types */
/**  Why a command could not answer. */
export type CommandError = 
/**  No compendium is installed; nothing to search. */
{ kind: "no-compendium" } | 
/**  No entry with that id, or none the viewer may see. */
{ kind: "not-found"; id: string } | 
/**  The store failed underneath. */
{ kind: "store"; message: string } | 
/**  The scene refused the change, or could not be saved. */
{ kind: "scene"; message: string };

/**  One compendium entry: the system-agnostic envelope plus the system's data. */
export type Entry = {
	id: EntryId,
	/**  The entry's category within its system: `monster`, `spell`, `item`, and so on. */
	type: string,
	name: string,
	/**  Provenance: the book, module, or homebrew collection the entry came from. */
	source: string,
	tags: string[],
	/**  Who may see the entry at all: its name, tags, and body. */
	visibility: Visibility,
	/**  Who may see `data`. A monster can be known by name while its statblock stays DM-only. */
	data_visibility: Visibility,
	/**  Prose body, markdown. */
	body: string,
	/**  The per-system structured blob; its schema belongs to the game system, not the envelope. */
	data: JsonValue,
};

/**  Stable identifier of an entry; links never break because ids never change. */
export type EntryId = string;

/**  A square grid, in map pixels; hex grids arrive with hexpunk's lattice. */
export type Grid = {
	cell_size: number,
	origin_x: number,
	origin_y: number,
	cols: number,
	rows: number,
};

/**  One row of a search result. */
export type Hit = {
	id: EntryId,
	type: string,
	name: string,
	source: string,
	tags: string[],
	/**
	 *  Rule 3 rungs less the rule 5 bonus; lower is better. Comparable only
	 *  within one result list.
	 */
	rank: number,
	/**  Rule 4 penalties; lower is better. */
	penalty: number,
};

/**
 *  The TypeScript shape of `serde_json::Value`, used only as a type witness
 *  through `#[specta(type = JsonValue)]`; the fields themselves stay
 *  `serde_json::Value`. The exporter refuses the 64-bit integers inside
 *  `serde_json::Number` because JavaScript would truncate them; JSON numbers
 *  are JavaScript numbers on that side whatever we say, so this names that
 *  truth once. JSON `null` needs no variant: specta renders an untagged enum
 *  with `null` in its union.
 */
export type JsonValue = boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

/**  The manifest at a module's root, `module.json`. */
export type Manifest = {
	id: string,
	name: string,
	system: string,
	systemVersion: string,
	version: string,
	license: string,
	/**  The notice the licence requires; shown in the credits view. */
	attribution: string,
	/**  Free-form provenance: where the content was imported from. */
	upstream?: JsonValue | null,
};

/**  The map image under the grid. */
export type MapImage = {
	url: string,
	width: number,
	height: number,
};

/**  A scene as the board shows it. */
export type Scene = {
	id: string,
	name: string,
	grid: Grid,
	map: MapImage | null,
	tokens: Token[],
	/**  Counter behind the ids this scene mints for new tokens. */
	next_token: number,
};

/**  A ranked search result with the time the core spent on it. */
export type SearchResponse = {
	hits: Hit[],
	/**  Time spent in the core, in microseconds. */
	elapsed_us: number,
	/**  How many entries the catalogue held when it answered. */
	catalogue_size: number,
};

/**  Something standing on a cell. */
export type Token = {
	id: string,
	name: string,
	/**  The short mark drawn on the disc: initials, at most two letters. */
	label: string,
	col: number,
	row: number,
	/**  Degrees clockwise from north. */
	facing: number,
	/**  The compendium entry this token stands for, when it stands for one. */
	entry: EntryId | null,
	visibility: Visibility,
};

/**
 *  Who may see something. Ordered from most open to most restricted, so a
 *  viewer sees everything at or below their own tier.
 */
export type Visibility = 
/**  Anyone, including a player who has never met the thing. */
"world" | 
/**  The party: players at the table. */
"party" | 
/**  The DM only. */
"dm";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

