// Generated from apps/table/src-tauri by tauri-specta. Do not edit;
// run `bun run schema` after changing the command surface.

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  Rank the compendium against `query` for a viewer of `viewer` tier. */
	search: (query: string, viewer: Visibility, limit: number | null, filters: Filter[] | null) => typedError<SearchResponse, CommandError>(__TAURI_INVOKE("search", { query, viewer, limit, filters })),
	/**  One entry as `viewer` may see it. */
	getEntry: (id: EntryId, viewer: Visibility) => typedError<Entry, CommandError>(__TAURI_INVOKE("get_entry", { id, viewer })),
	/**  The manifests of every module in the compendium, for the credits view. */
	modules: () => typedError<Manifest[], CommandError>(__TAURI_INVOKE("modules")),
	/**
	 *  The system the compendium was seeded for: its categories, kinds,
	 *  facets and the tray's controls. `None` when the seeder was given none.
	 */
	system: () => typedError<{
	id: string,
	name: string,
	/**  Category id to label: the tabs of the box, in this order. */
	categories?: { [key in string]: string },
	/**  Entry kind to what it is called and where it is grouped. */
	kinds?: { [key in string]: KindSpec },
	/**  Per kind, facet name to how it is read from `data`. */
	facets?: { [key in string]: { [key in string]: FacetSpec } },
	/**  Per kind, the tray's controls in order. */
	controls?: { [key in string]: ControlSpec[] },
	/**  Per kind, the lists in `data` whose items are named parts. */
	parts?: { [key in string]: PartSpec[] },
} | null, CommandError>(__TAURI_INVOKE("system")),
	/**
	 *  The text values each facet holds across the compendium, for the tray's
	 *  chips: schools, creature types, categories.
	 */
	facetValues: () => typedError<{ [key in string]: string[] }, CommandError>(__TAURI_INVOKE("facet_values")),
	/**  The scene the board shows. */
	getScene: () => typedError<Scene, CommandError>(__TAURI_INVOKE("get_scene")),
	/**  Commit a token's move: the release of a drag, or a keyboard step. */
	moveToken: (id: string, col: number, row: number, facing: number) => typedError<Scene, CommandError>(__TAURI_INVOKE("move_token", { id, col, row, facing })),
	/**  Stand a compendium entry on a cell as a new token. */
	placeEntry: (id: EntryId, col: number, row: number) => typedError<Scene, CommandError>(__TAURI_INVOKE("place_entry", { id, col, row })),
	/**  Take a token off the board. */
	removeToken: (id: string) => typedError<Scene, CommandError>(__TAURI_INVOKE("remove_token", { id })),
};

/* Types */
/**
 *  One cell of a switch rail: the facet and value it stands for. A cell
 *  without a value stands for a yes.
 */
export type Cell = {
	facet: string,
	value?: FacetValue,
	label: string,
};

/**  Why a command could not answer. */
export type CommandError = 
/**  No compendium is installed; nothing to search. */
{ kind: "no-compendium" } | 
/**  No entry with that id, or none the viewer may see. */
{ kind: "not-found"; id: string } | 
/**  The store failed underneath. */
{ kind: "store"; message: string } | 
/**  The scene refused the change, or could not be saved. */
{ kind: "scene"; message: string };

/**  How a facet filter compares. */
export type Compare = "eq" | "lt" | "le" | "gt" | "ge";

/**
 *  The five controls of the tray. `Rail` paints spans over an ordered
 *  scale; `Switch` is the same strip with each cell its own switch.
 */
export type ControlKind = "rail" | "switch" | "slider" | "chips" | "select";

/**  One control of the tray. */
export type ControlSpec = {
	control: ControlKind,
	label: string,
	/**  The facet a rail, slider, chips or select edits. */
	facet?: string | null,
	/**
	 *  The ordered values of a rail, slider or select. Chips take theirs
	 *  from the data.
	 */
	stops?: Stop[],
	/**
	 *  The cells of a switch rail, as rows shown side by side. A manifest
	 *  may write one flat row.
	 */
	cells?: Cell[][],
	/**  A control shown beside this one (the switches beside a range slider). */
	beside?: ControlSpec | null,
};

/**  One compendium entry: the system-agnostic envelope plus the system's data. */
export type Entry = {
	id: EntryId,
	/**  The entry's category within its system: `monster`, `spell`, `item`, and so on. */
	type: string,
	name: string,
	/**  Provenance: the book, module, or homebrew collection the entry came from. */
	source: string,
	tags: string[],
	/**  Who may see the entry at all: its name, tags, and body. */
	visibility: Visibility,
	/**  Who may see `data`. A monster can be known by name while its statblock stays DM-only. */
	data_visibility: Visibility,
	/**  Prose body, markdown. */
	body: string,
	/**  The per-system structured blob; its schema belongs to the game system, not the envelope. */
	data: JsonValue,
	/**  Filterable facts read from `data` by the system manifest at seed time. */
	facets?: { [key in string]: FacetValue },
	/**
	 *  Named parts of `data` read by the system manifest at seed time, so
	 *  search can find an entry by a trait, an action, or a feature.
	 */
	parts?: Part[],
};

/**  Stable identifier of an entry; links never break because ids never change. */
export type EntryId = string;

/**  How one facet is read from an entry's `data`, and the words that name it. */
export type FacetSpec = {
	/**  Dotted path into `data`. */
	path: string,
	type: FacetType,
	/**  Words the parser accepts for the facet's name. */
	words?: string[],
	/**  Words that stand for one value of the facet (`cantrip` for level 0). */
	aliases?: { [key in string]: FacetValue },
	/**
	 *  Text facets only: the value is the first of these words found in the
	 *  text at `path`, so one string can feed several facets.
	 */
	pick?: string[],
	/**
	 *  Number facets only: words in another field that stand for a number
	 *  beyond any real one (a range of sight).
	 */
	sentinels?: Sentinels | null,
	/**  Display unit, never stored with the value. */
	unit?: string | null,
};

export type FacetType = "number" | "text" | "bool";

/**
 *  A facet: one filterable fact about an entry, read from its data by the
 *  system's manifest at seed time (`level`, `school`, `cr`, `ritual`), so
 *  search can answer `level<=3` without opening the data.
 */
export type FacetValue = number | null | string | boolean;

/**
 *  A filter: what an entry must satisfy to be listed at all. Values are
 *  normalised like everything else. A list of filters is a conjunction;
 *  `Any` and `Not` give it the rest of the shapes a phrase can take.
 */
export type Filter = { filter: "kind"; value: string } | { filter: "tag"; value: string } | { filter: "source"; value: string } | 
/**  A facet of the entry's data: `level<=3`, `school:evocation`. */
{ filter: "facet"; name: string; compare: Compare; value: string } | 
/**  At least one of these passes. */
{ filter: "any"; items: Filter[] } | 
/**  This one does not pass. */
{ filter: "not"; item: Filter };

/**  A square grid, in map pixels; hex grids arrive with hexpunk's lattice. */
export type Grid = {
	cell_size: number,
	origin_x: number,
	origin_y: number,
	cols: number,
	rows: number,
};

/**  One row of a search result. */
export type Hit = {
	id: EntryId,
	type: string,
	name: string,
	source: string,
	tags: string[],
	/**
	 *  The part the query found this entry by, when its best match was a
	 *  trait, an action or a feature rather than the entry itself.
	 */
	part: Part | null,
	/**
	 *  Rule 3 rungs less the rule 5 bonus; lower is better. Comparable only
	 *  within one result list.
	 */
	rank: number,
	/**  Rule 4 penalties; lower is better. */
	penalty: number,
};

/**
 *  The TypeScript shape of `serde_json::Value`, used only as a type witness
 *  through `#[specta(type = JsonValue)]`; the fields themselves stay
 *  `serde_json::Value`. The exporter refuses the 64-bit integers inside
 *  `serde_json::Number` because JavaScript would truncate them; JSON numbers
 *  are JavaScript numbers on that side whatever we say, so this names that
 *  truth once. JSON `null` needs no variant: specta renders an untagged enum
 *  with `null` in its union.
 */
export type JsonValue = boolean | number | null | string | JsonValue[] | { [key in string]: JsonValue };

/**
 *  What a kind is called, where the box groups it, which words mean it,
 *  and what an entry of it may be seen by unless the entry says otherwise.
 */
export type KindSpec = {
	name: string,
	category: string,
	words?: string[],
	visibility?: Visibility | null,
	data_visibility?: Visibility | null,
};

/**  The manifest at a module's root, `module.json`. */
export type Manifest = {
	id: string,
	name: string,
	system: string,
	systemVersion: string,
	version: string,
	license: string,
	/**  The notice the licence requires; shown in the credits view. */
	attribution: string,
	/**  Free-form provenance: where the content was imported from. */
	upstream?: JsonValue | null,
};

/**  The map image under the grid. */
export type MapImage = {
	url: string,
	width: number,
	height: number,
};

/**
 *  A named part of an entry's data: a creature's trait or action, a
 *  class's feature. The manifest names the lists that carry them, the
 *  seeder stores their names, and search matches them as a field, so
 *  "pack tactics" finds its bearers and the tile can say which part hit.
 */
export type Part = {
	/**  What kind of part, as the system calls it: "Trait", "Action". */
	label: string,
	name: string,
};

/**
 *  A list inside `data` whose items carry a name: `traits`, `actions`,
 *  a class's `features`. Each item becomes a searchable part.
 */
export type PartSpec = {
	/**  Dotted path to the list. */
	path: string,
	/**  What the parts are called: "Trait", "Action", "Feature". */
	label: string,
	/**  The item field holding the name. */
	key?: string,
};

/**  A scene as the board shows it. */
export type Scene = {
	id: string,
	name: string,
	grid: Grid,
	map: MapImage | null,
	tokens: Token[],
	/**  Counter behind the ids this scene mints for new tokens. */
	next_token: number,
};

/**  A ranked search result with the time the core spent on it. */
export type SearchResponse = {
	hits: Hit[],
	/**  Time spent in the core, in microseconds. */
	elapsed_us: number,
	/**  How many entries the catalogue held when it answered. */
	catalogue_size: number,
	/**
	 *  What the parser made of the typed text: the stretches that became
	 *  filters, and those set aside as meaning nothing here.
	 */
	understood: Understood[],
};

/**  Words at `path` that stand for a number. */
export type Sentinels = {
	path: string,
	values: { [key in string]: number | null },
};

/**
 *  One value on a rail, slider or select, with the label it shows when
 *  the value itself will not do.
 */
export type Stop = {
	value: FacetValue,
	label?: string | null,
};

/**  The system manifest. */
export type SystemManifest = {
	id: string,
	name: string,
	/**  Category id to label: the tabs of the box, in this order. */
	categories?: { [key in string]: string },
	/**  Entry kind to what it is called and where it is grouped. */
	kinds?: { [key in string]: KindSpec },
	/**  Per kind, facet name to how it is read from `data`. */
	facets?: { [key in string]: { [key in string]: FacetSpec } },
	/**  Per kind, the tray's controls in order. */
	controls?: { [key in string]: ControlSpec[] },
	/**  Per kind, the lists in `data` whose items are named parts. */
	parts?: { [key in string]: PartSpec[] },
};

/**  Something standing on a cell. */
export type Token = {
	id: string,
	name: string,
	/**  The short mark drawn on the disc: initials, at most two letters. */
	label: string,
	col: number,
	row: number,
	/**  Degrees clockwise from north. */
	facing: number,
	/**  The compendium entry this token stands for, when it stands for one. */
	entry: EntryId | null,
	visibility: Visibility,
};

/**
 *  A stretch of the typed query the parser dealt with: the filter it
 *  became, or nothing when the stretch was set aside as meaning nothing
 *  here (a connective on its own, a word no entry has).
 */
export type Understood = {
	/**  Char offsets into the typed text. */
	start: number,
	end: number,
	filter: Filter | null,
	/**
	 *  The tray said otherwise about this facet, so the words were set
	 *  aside; they stay in the text, greyed.
	 */
	overruled?: boolean,
};

/**
 *  Who may see something. Ordered from most open to most restricted, so a
 *  viewer sees everything at or below their own tier.
 */
export type Visibility = 
/**  Anyone, including a player who has never met the thing. */
"world" | 
/**  The party: players at the table. */
"party" | 
/**  The DM only. */
"dm";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

